baseURL = "https://www.example.com"
#CanonifyURLs=true

languageCode = "en-us"
theme = "ramium"

title = "Charandeep Kapoor"
disqusShortname = ""
googleAnalytics = ""
summaryLength = 40
pluralizeListTitles = false
enableemoji = false

[params]
    description = "Charan's blog"
    googleSearch = ""
    adsense = ""
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page

    tagsInHome = 40
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Posts"
        weight = 2
        url = "/posts/"
            
    [[menu.main]]
        name = "Author"
        url = "/author/"
        weight = 3
